In [1]:
!pip install numpy
import numpy as np
l1 = [1,2,3]
l2 = [[1,2,3],[4,5,6]]
a1 = np.array(l1)
a2 = np.array(l2)
s1 = a1.shape
s2 = a2.shape
print(s1)
print(s2)

(3,)
(2, 3)


In [3]:
#Addition & Subtraction
aa = a1 + a2
sa = a1 - a2
print(aa)
print(sa)
print(aa.shape)
print(sa.shape)

[[2 4 6]
 [5 7 9]]
[[ 0  0  0]
 [-3 -3 -3]]
(2, 3)
(2, 3)


In [6]:
#SQRT & MIN & SUM & MAX & MEAN
print(np.sqrt(a1),'\n', np.sqrt(a2))
print(a1.sum(),'\n', a2.sum())
print(a1.min(),'\n', a2.min())
print(a1.max(),'\n', a2.max())
print(np.mean(a1),'\n', np.mean(a2))

[1.         1.41421356 1.73205081] 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
6 
 21
1 
 1
3 
 6
2.0 
 3.5


In [9]:
#Individual axis sum
a3 = np.array([[1,2,3],[4,5,6]])
print(np.sum(a3, axis=0))
print(np.sum(a3, axis=1))

[5 7 9]
[ 6 15]


In [13]:
#MATRIX MULTIPLICATION
'''we use a function called matmul from numpy module'''
l4 = [1,2,3]
l5 = [[1,2,3],[4,5,6],[7,8,10]]
m = np.matmul(l4,l5)
print(m)
print("Shape : ", m.shape)

[30 36 45]
Shape :  (3,)


In [14]:
#MATRIX INVERSE
'''we use a function called inv from numpy module
or we can also use np.linalg.inv'''
print(np.linalg.inv(l5))

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
